schema: graphql/schema.json
documents: "graphql/**/*.gql"
extensions:
  codegen:
    overwrite: true
    hooks:
      afterAllFileWrite:
        - pnpm eslint:fix
        - pnpm prettier:fix
    generates:
      graphql/generated.tsx:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-react-apollo"
          - "typescript-resolvers"
        config:
          withComponent: false
          withHOC: false
          withHooks: true
          useIndexSignature: true
          exportFragmentSpreadSubTypes: true
      graphql/introspection-result.ts:
        plugins:
          - fragment-matcher
