query PendingSupervisionRequests {
  me {
    sentSupervisionRequests {
      player {
        ...playerFields
      }
      approvals {
        approved
        approver {
          id
          name
        }
      }
    }
  }
}
