fragment gameVersionFields on GameVersion {
  id
  versionNumber
  statDescriptions {
    ...statDescriptionFields
  }
  game {
    name
  }
  metrics {
    numericStats {
      stat {
        id
        name
      }
      globalAverage
    }
    enumStats {
      stat {
        id
        name
      }
      global {
        value
        occurences
      }
    }
  }
}
