fragment matchFields on Match {
  id
  gameVersion {
    ...gameVersionFields
  }
  players {
    ...playerFields
  }
  stats {
    value
    statDescription {
      ...statDescriptionFields
    }
    player {
      ...playerFields
    }
  }
}
